endpoints:
  actuator:
    enabled: false
  autoconfig:
    enabled: false
  beans:
    enabled: false
  configprops:
    enabled: false
  docs:
    enabled: false
  dump:
    enabled: false
  env:
    enabled: false
  heapdump:
    enabled: false
  logfile:
    enabled: false
  loggers:
      enabled: false
  trace:
      enabled: false

logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn

management:
  security:
    enabled: false

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048

spring:
  jackson:
    serialization:
     write-dates-as-timestamps: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

initializr:
  env:
    boms:
      camel:
        groupId: org.apache.camel
        artifactId: camel-spring-boot-dependencies
        versionProperty: camel.version
        mappings:
          - versionRange: "[1.4.0.RELEASE,1.5.0.RELEASE)"
            version: 2.18.5
          - versionRange: "[1.5.0.RELEASE,2.0.0.M1)"
            version: 2.20.2
    gradle:
      dependency-management-plugin-version: 0.6.0.RELEASE
    kotlin:
      default-version: 1.2.20
  dependencies:
    - name: Endpoints
      bom: camel
      content:
        - name: RESTful
          id: rest-endpoint
          groupId: org.apache.camel
          artifactId: camel-servlet-starter
          facets:
            - rest-endpoint
          links:
            - rel: guide
              href: http://camel.apache.org/rest-dsl.html
        - name: File
          id: file-endpoint
          facets:
            - file-endpoint
          links:
            - rel: guide
              href: http://camel.apache.org/file2.html         
    - name: Core
      content:
        - name: Camel Core
          id: camel-core
          groupId: org.apache.camel
          artifactId: camel-spring-boot-starter
          bom: camel
          facets:
            - camel
    - name: Web
      content:
        - name: Web
          id: web
          description: Web Support
          weight: 100
          facets:
            - web
          links:
            - rel: guide
              href: https://spring.io/guides/gs/rest-service/
              description: Building a RESTful Web Service
            - rel: reference
              href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-developing-web-applications
            - rel: guide
              href: https://spring.io/guides/gs/serving-web-content/
              description: Serving Web Content with Spring MVC
            - rel: guide
              href: https://spring.io/guides/tutorials/bookmarks/
              description: Building REST services with Spring
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 1.8
      name: 8
      default: true
  languages:
    - name: Java
      id: java
      default: true
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.4.BUILD-SNAPSHOT
      default: false
    - name: 1.2.3
      id: 1.2.3.RELEASE
      default: true
    - name: 1.1.12
      id: 1.1.12.RELEASE
      default: false
